import { BaseInteractions } from "../global";

export const soloWord = {
  [BaseInteractions.Take]: [
    "take",
    "get",
    "pick",
    "collect",
    "seize",
    "acquire",
    "obtain",
    "snatch",
    "receive",
    "appropriate",
    "fetch",
  ],
  [BaseInteractions.Examine]: [
    "examine",
    "grab",
    "hold",
    "clutch",
    "grip",
    "check",
    "inspect",
    "investigate",
    "probe",
    "appraise",
    "review",
    "scan",
    "scrutinize",
    "study",
    "survey",
    "vet",
    "view",
    "peruse",
    "research",
  ],
  [BaseInteractions.Use]: [
    "use",
    "apply",
    "control",
    "employ",
    "manipulate",
    "operate",
    "utilise",
    "utilize",
    "wield",
    "work",
  ],
  [BaseInteractions.Go]: [
    "go",
    "flee",
    "advance",
    "move",
    "walk",
    "progress",
    "travel",
    "depart",
    "escape",
    "exit",
    "withdraw",
    "vamoose",
  ],
  [BaseInteractions.Items]: [
    "items",
    "inventory",
    "stuff",
    "equipment",
    "gear",
    "loot",
    "things",
    "kit",
  ],
  [BaseInteractions.Eat]: [
    "eat",
    "consume",
    "bite",
    "devour",
    "ingest",
    "swallow",
  ],
};

export const DoubleTerm = {
  [BaseInteractions.Examine]: ["look at"],
};
